# Generated by Django 3.2.7 on 2021-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner_unversity',
            new_name='owner_university',
        ),
    ]
