# Generated by Django 3.2.7 on 2021-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_owner_unversity_room_owner_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='lap_time',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
