# Generated by Django 3.2.7 on 2021-11-22 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_univ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('opponent_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_room', to='account.univ')),
                ('owner_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_room', to='account.univ')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('lap_time', models.CharField(blank=True, max_length=63, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user')),
            ],
        ),
    ]
