# Generated by Django 3.2.7 on 2021-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_join',
            field=models.IntegerField(default=0),
        ),
    ]
