# Generated by Django 3.2.7 on 2021-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_max_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.TextField(default='_'),
        ),
    ]
