# Generated by Django 3.1.4 on 2021-11-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_hased_id_user_hashed_id'),
        ('feed', '0004_auto_20211125_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user'),
        ),
    ]
