# Generated by Django 3.2.7 on 2021-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_univ_domain'),
        ('game', '0004_alter_room_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('is_home', models.BooleanField(default=True)),
                ('max_join', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('away_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_away_univ', to='account.univ')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_invitor', to='account.user')),
                ('home_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_home_univ', to='account.univ')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_receiver', to='account.user')),
            ],
        ),
    ]
