# Generated by Django 3.1.4 on 2021-11-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_hased_id_user_hashed_id'),
        ('feed', '0005_auto_20211125_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='game_map',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user'),
        ),
    ]
