# Generated by Django 3.2.7 on 2021-11-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
