# Generated by Django 3.2.7 on 2021-11-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_univ_domain'),
        ('game', '0007_entrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default='-')),
                ('score', models.IntegerField(default=0)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_room', to='game.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_user', to='account.user')),
            ],
        ),
    ]
