# Generated by Django 3.2.7 on 2021-11-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
