# Generated by Django 3.2.7 on 2021-11-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_univ_domain'),
        ('game', '0010_auto_20211128_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='opponent_univ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_room', to='account.univ'),
        ),
    ]
