# Generated by Django 3.2.7 on 2021-11-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_room_opponent_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='game_map',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
