# Generated by Django 3.2.7 on 2021-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_ranking_game_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
