# Generated by Django 3.2.7 on 2021-10-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.TextField(verbose_name='kakao_id')),
                ('kakao_email', models.EmailField(max_length=254, verbose_name='kakao_email')),
                ('kakao_name', models.TextField(verbose_name='kakao_name')),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='register_date')),
                ('univ_name', models.TextField(null=True, verbose_name='univ_name')),
                ('is_active', models.BooleanField(default=False)),
                ('is_first_visit', models.BooleanField(default=True)),
            ],
        ),
    ]
