# Generated by Django 3.2.7 on 2021-10-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211004_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_first_visit',
            new_name='first_visit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='univ_verified',
        ),
    ]
