# Generated by Django 3.2.7 on 2021-10-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211004_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hased_id',
            new_name='hashed_id',
        ),
    ]
