# Generated by Django 3.1.4 on 2021-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_hased_id_user_hashed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='univ',
            fields=[
                ('name', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('domain', models.CharField(default=' ', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
