# Generated by Django 3.2.7 on 2021-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ',
            name='domain',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
