# Generated by Django 3.2.7 on 2021-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_univ_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(max_length=15, null=True, verbose_name='nickname'),
        ),
    ]
